server:
  port: 8084

spring:
  application:
    name: function-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    function:
      definition: generateTicket
    stream:
      bindings:
        generateTicket-in-0:
          destination: order_exchange
          group: function_queue_group
          content-type: application/json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
